#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
cd "${repo_dir}"

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "Run setup.sh on a Nibi login node." >&2
  exit 1
fi

if ! type module >/dev/null 2>&1; then
  if [[ -r /cvmfs/soft.computecanada.ca/config/profile/bash.sh ]]; then
    # shellcheck disable=SC1091
    source /cvmfs/soft.computecanada.ca/config/profile/bash.sh
  fi
fi
type module >/dev/null 2>&1 || {
  echo "Alliance module environment not found. Run this on nibi.alliancecan.ca." >&2
  exit 1
}

module --force purge
module load StdEnv/2023
module load python/3.11
module load cuda
module load ffmpeg

for command_name in curl git python3 ffmpeg; do
  command -v "${command_name}" >/dev/null 2>&1 || {
    echo "${command_name} is unavailable after loading Nibi modules." >&2
    exit 1
  }
done

project_root=${H3_PROJECT_ROOT:-"${repo_dir}"}
[[ ! -e "${project_root}" || -d "${project_root}" ]] || {
  echo "H3_PROJECT_ROOT exists but is not a directory: ${project_root}" >&2
  exit 1
}

data_dir=${H3_DATA_DIR:-"${project_root}/minimax-h3"}
env_dir="${data_dir}/envs/h3"
model_dir="${data_dir}/models/MiniMax-H3"
modules_file="${data_dir}/nibi-modules.sh"

mkdir -p \
  "${data_dir}/envs" \
  "${data_dir}/cache/uv" \
  "${data_dir}/cache/xdg" \
  "${data_dir}/cache/huggingface" \
  "${model_dir}" \
  outputs logs .run

if ! command -v uv >/dev/null 2>&1; then
  echo "Installing uv in your user account ..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="${HOME}/.local/bin:${HOME}/.cargo/bin:${PATH}"
fi
command -v uv >/dev/null 2>&1 || { echo "uv installation failed." >&2; exit 1; }

export UV_CACHE_DIR="${data_dir}/cache/uv"
export XDG_CACHE_HOME="${data_dir}/cache/xdg"
export HF_HUB_CACHE="${data_dir}/cache/huggingface"

venv_link="${repo_dir}/.venv"
if [[ -L "${venv_link}" ]]; then
  if ! python3 - "${venv_link}" "${env_dir}" <<'PY'
import os
import sys

current = os.path.realpath(sys.argv[1])
expected = os.path.realpath(sys.argv[2])
if current != expected:
    print(f"{sys.argv[1]} already points to {current}, not {expected}.", file=sys.stderr)
    raise SystemExit(1)
PY
  then
    echo "Move that link aside, then run ./setup.sh again." >&2
    exit 1
  fi
elif [[ -e "${venv_link}" ]]; then
  echo "${venv_link} already exists and is not the Nibi environment link." >&2
  echo "Move it aside, then run ./setup.sh again." >&2
  exit 1
fi

echo "Creating one uv environment for MiniMax H3 under: ${data_dir}"
UV_PROJECT_ENVIRONMENT="${env_dir}" UV_LINK_MODE=copy \
  uv sync --frozen --extra inference --python "$(command -v python3)"

[[ -L "${venv_link}" ]] || ln -s "${env_dir}" "${venv_link}"

{
  echo '# Generated by setup.sh on Nibi.'
  echo 'module --force purge'
  IFS=':' read -r -a loaded_modules <<<"${LOADEDMODULES:-}"
  for loaded_module in "${loaded_modules[@]}"; do
    [[ -n "${loaded_module}" ]] && printf 'module load %q\n' "${loaded_module}"
  done
} >"${modules_file}"
chmod 600 "${modules_file}"

if [[ ! -f .env ]]; then
  cp .env.example .env
  secret=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')
  python3 - "${secret}" <<'PY'
from pathlib import Path
import sys

path = Path(".env")
path.write_text(path.read_text().replace("change-me-to-a-long-random-secret", sys.argv[1]))
PY
fi

python3 - ".env" "${data_dir}" "${model_dir}" "${env_dir}" "${modules_file}" <<'PY'
from pathlib import Path
import shlex
import sys

path = Path(sys.argv[1])
data_dir, model_dir, env_dir, modules_file = sys.argv[2:]
updates = {
    "H3_PLATFORM": "nibi",
    "H3_SLURM_ACCOUNT": "def-denilson",
    "H3_DATA_DIR": data_dir,
    "H3_ENV_DIR": env_dir,
    "H3_MODEL_DIR": model_dir,
    "H3_MODEL_PATH": model_dir,
    "H3_MODEL_REVISION": "42ed227ee7df40d41602854ae760620d6eb651fe",
    "H3_GATEWAY_BIN": env_dir + "/bin/h3-gateway",
    "H3_SGLANG_BIN": env_dir + "/bin/sglang",
    "H3_HF_BIN": env_dir + "/bin/hf",
    "H3_MODULES_FILE": modules_file,
    "UV_CACHE_DIR": data_dir + "/cache/uv",
    "XDG_CACHE_HOME": data_dir + "/cache/xdg",
    "HF_HUB_CACHE": data_dir + "/cache/huggingface",
    "H3_PROFILE": "h100x1",
}
lines = path.read_text().splitlines()
seen = set()
result = []
for line in lines:
    key = line.split("=", 1)[0] if "=" in line and not line.startswith("#") else None
    if key in updates:
        result.append(f"{key}={shlex.quote(updates[key])}")
        seen.add(key)
    else:
        result.append(line)
for key, value in updates.items():
    if key not in seen:
        result.append(f"{key}={shlex.quote(value)}")
path.write_text("\n".join(result) + "\n")
PY
chmod 600 .env

echo
echo "Nibi environment ready under: ${data_dir}"
echo "Activate it with: source .venv/bin/activate"
echo "Then run on this login node: ./download_models.sh"
