from __future__ import annotations

import os
import shlex
import shutil
import socket
import stat
import subprocess
import sys
import time
import tomllib
from pathlib import Path

import pytest


REPO = Path(__file__).resolve().parents[1]
SETUP = REPO / "setup.sh"
DOWNLOAD = REPO / "download_models.sh"
SERVER = REPO / "run_server.sh"
GENERATE = REPO / "generate.sh"


def _executable(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
    path.chmod(0o755)
    return path


def _copy_script(source: Path, root: Path) -> Path:
    destination = root / source.name
    root.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    helper = REPO / "scripts/require_active_env.sh"
    if helper.exists():
        (root / "scripts").mkdir(exist_ok=True)
        shutil.copy2(helper, root / "scripts/require_active_env.sh")
    return destination


def _fake_command(bin_dir: Path, name: str, log: Path, *, exit_code: int = 0) -> Path:
    return _executable(
        bin_dir / name,
        "#!/usr/bin/env bash\n"
        f"printf '%s\\n' {name!r}\" $*\" >> {str(log)!r}\n"
        f"exit {exit_code}\n",
    )


def _setup_sandbox(tmp_path: Path, *, include_uv: bool = True) -> tuple[Path, Path, Path, Path]:
    root = tmp_path / "repo with spaces"
    script = _copy_script(SETUP, root)
    log = tmp_path / "calls.log"
    bin_dir = tmp_path / "fake bin"
    bin_dir.mkdir()

    shutil.copy2(REPO / ".env.example", root / ".env.example")
    _executable(bin_dir / "uname", "#!/usr/bin/env bash\necho Linux\n")
    for name in ("curl", "git", "ffmpeg"):
        _fake_command(bin_dir, name, log)
    if include_uv:
        _fake_command(bin_dir, "uv", log)

    bash_env = tmp_path / "bash-env"
    bash_env.write_text(
        "module() {\n"
        "  printf 'module:%s\\n' \"$*\" >> \"$CALL_LOG\"\n"
        "  if [[ \"$1\" == --force && \"$2\" == purge ]]; then LOADEDMODULES=; export LOADEDMODULES; fi\n"
        "  if [[ \"$1\" == load ]]; then LOADEDMODULES=${LOADEDMODULES:+$LOADEDMODULES:}$2; export LOADEDMODULES; fi\n"
        "}\n"
    )
    return root, script, log, bash_env


def _setup_env(tmp_path: Path, log: Path, bash_env: Path, project_root: Path) -> dict[str, str]:
    env = os.environ.copy()
    env.update(
        PATH=f"{tmp_path / 'fake bin'}{os.pathsep}{env['PATH']}",
        CALL_LOG=str(log),
        BASH_ENV=str(bash_env),
        H3_PROJECT_ROOT=str(project_root),
        HOME=str(tmp_path / "home"),
        USER="tester",
    )
    return env


def test_setup_builds_nibi_project_environments_and_is_idempotent(tmp_path: Path) -> None:
    root, script, log, bash_env = _setup_sandbox(tmp_path)
    project_root = tmp_path / "project storage"
    env = _setup_env(tmp_path, log, bash_env, project_root)

    for _ in range(2):
        result = subprocess.run(
            [str(script)], cwd=tmp_path, env=env, text=True, capture_output=True, check=False
        )
        assert result.returncode == 0, result.stderr
        assert f"Nibi environment ready under: {project_root / 'minimax-h3'}" in result.stdout

    calls = log.read_text().splitlines()
    expected_modules = [
        "module:--force purge",
        "module:load StdEnv/2023",
        "module:load python/3.11",
        "module:load cuda",
        "module:load ffmpeg",
    ]
    assert calls[:5] == expected_modules
    assert calls.count("uv sync --frozen --extra inference --python " + shutil.which("python3")) == 2
    data = project_root / "minimax-h3"
    for directory in ("envs", "cache/uv", "cache/xdg", "cache/huggingface", "models/MiniMax-H3"):
        assert (data / directory).is_dir()
    for directory in ("outputs", "logs", ".run"):
        assert (root / directory).is_dir()
    snapshot = (data / "nibi-modules.sh").read_text().splitlines()
    assert snapshot == ["# Generated by setup.sh on Nibi.", "module --force purge", *[x.replace("module:", "module ") for x in expected_modules[1:]]]
    assert not any("sudo" in call or "apt-get" in call for call in calls)
    env_text = (root / ".env").read_text()
    key = next(line.split("=", 1)[1] for line in env_text.splitlines() if line.startswith("H3_GATEWAY_API_KEY="))
    assert key and key != "change-me-to-a-long-random-secret"
    env_dir = data / "envs/h3"
    assert (root / ".venv").is_symlink()
    assert os.path.realpath(root / ".venv") == os.path.realpath(env_dir)
    assert f"H3_ENV_DIR={shlex.quote(str(env_dir))}" in env_text
    assert f"H3_GATEWAY_BIN={shlex.quote(str(env_dir / 'bin/h3-gateway'))}" in env_text
    assert f"H3_SGLANG_BIN={shlex.quote(str(env_dir / 'bin/sglang'))}" in env_text
    assert f"H3_HF_BIN={shlex.quote(str(env_dir / 'bin/hf'))}" in env_text


def test_setup_requires_alliance_module_environment(tmp_path: Path) -> None:
    _, script, _, _ = _setup_sandbox(tmp_path)
    env = os.environ.copy()
    env.update(PATH=f"{tmp_path / 'fake bin'}{os.pathsep}{env['PATH']}", H3_PROJECT_ROOT=str(tmp_path / "project"))
    env.pop("BASH_ENV", None)
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "Alliance module environment not found" in result.stderr
    assert "/cvmfs/soft.computecanada.ca/config/profile/bash.sh" in script.read_text()


def test_setup_installs_uv_and_uses_new_binary_in_same_run(tmp_path: Path) -> None:
    root, script, log, bash_env = _setup_sandbox(tmp_path, include_uv=False)
    home = tmp_path / "home with spaces"
    curl = tmp_path / "fake bin/curl"
    _executable(
        curl,
        "#!/usr/bin/env bash\n"
        "printf 'curl:%s\\n' \"$*\" >> \"$CALL_LOG\"\n"
        "cat <<'INSTALLER'\n"
        "mkdir -p \"$HOME/.local/bin\"\n"
        "printf '#!/usr/bin/env bash\\nexit 0\\n' > \"$HOME/.local/bin/uv\"\n"
        "chmod +x \"$HOME/.local/bin/uv\"\n"
        "INSTALLER\n",
    )
    env = _setup_env(tmp_path, log, bash_env, tmp_path / "project")
    env["HOME"] = str(home)
    python = shutil.which("python3")
    assert python
    (tmp_path / "fake bin/python3").symlink_to(python)
    env["PATH"] = f"{tmp_path / 'fake bin'}:/usr/bin:/bin"
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 0, result.stderr
    assert "Installing uv in your user account" in result.stdout
    assert (home / ".local/bin/uv").is_file()
    assert "uv-install-bin" not in log.read_text()


def test_setup_defaults_to_repo_storage_and_supports_data_override(tmp_path: Path) -> None:
    root, script, log, bash_env = _setup_sandbox(tmp_path)
    custom_data = tmp_path / "large shared data"
    env = _setup_env(tmp_path, log, bash_env, tmp_path / "ignored")
    env.pop("H3_PROJECT_ROOT")
    env["H3_DATA_DIR"] = str(custom_data)
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 0, result.stderr
    assert (custom_data / "envs").is_dir()
    assert f"H3_DATA_DIR={shlex.quote(str(custom_data))}" in (root / ".env").read_text()


def test_setup_uses_repo_directory_when_project_root_is_unset(tmp_path: Path) -> None:
    root, script, log, bash_env = _setup_sandbox(tmp_path)
    env = _setup_env(tmp_path, log, bash_env, tmp_path / "ignored")
    env.pop("H3_PROJECT_ROOT")
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 0, result.stderr
    assert f"Nibi environment ready under: {root / 'minimax-h3'}" in result.stdout
    assert (root / "minimax-h3/envs").is_dir()
    assert os.path.realpath(root / ".venv") == os.path.realpath(root / "minimax-h3/envs/h3")


def test_setup_rejects_invalid_project_root_override(tmp_path: Path) -> None:
    _, script, log, bash_env = _setup_sandbox(tmp_path)
    env = _setup_env(tmp_path, log, bash_env, tmp_path / "ignored")
    invalid = tmp_path / "not-a-directory"
    invalid.write_text("x")
    env["H3_PROJECT_ROOT"] = str(invalid)
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "H3_PROJECT_ROOT exists but is not a directory" in result.stderr


def test_setup_preserves_existing_secret_and_custom_lines(tmp_path: Path) -> None:
    root, script, log, bash_env = _setup_sandbox(tmp_path)
    (root / ".env").write_text("H3_GATEWAY_API_KEY=keep-this-secret\nCUSTOM_SETTING=yes\nH3_MODEL_PATH=old\n")
    env = _setup_env(tmp_path, log, bash_env, tmp_path / "project")
    for _ in range(2):
        result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
        assert result.returncode == 0, result.stderr
    content = (root / ".env").read_text()
    assert content.count("H3_GATEWAY_API_KEY=keep-this-secret") == 1
    assert content.count("CUSTOM_SETTING=yes") == 1
    assert "H3_PLATFORM=nibi" in content
    assert "H3_SLURM_ACCOUNT=def-denilson" in content
    assert "H3_MODEL_PATH=old" not in content
    assert stat.S_IMODE((root / ".env").stat().st_mode) == 0o600


@pytest.mark.parametrize("conflict_kind", ["directory", "wrong_link"])
def test_setup_refuses_conflicting_repo_venv_before_installing(
    tmp_path: Path, conflict_kind: str
) -> None:
    root, script, log, bash_env = _setup_sandbox(tmp_path)
    if conflict_kind == "directory":
        (root / ".venv").mkdir()
    else:
        (root / ".venv").symlink_to(tmp_path / "some-other-env")
    env = _setup_env(tmp_path, log, bash_env, tmp_path / "project")
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "Move" in result.stderr and "aside" in result.stderr
    assert not any(call.startswith("uv sync") for call in log.read_text().splitlines())


def test_setup_accepts_existing_venv_link_through_project_alias(tmp_path: Path) -> None:
    root, script, log, bash_env = _setup_sandbox(tmp_path)
    canonical = tmp_path / "canonical-project"
    canonical.mkdir()
    alias = tmp_path / "project-alias"
    alias.symlink_to(canonical, target_is_directory=True)
    expected = alias / "minimax-h3/envs/h3"
    (root / ".venv").symlink_to(expected)
    env = _setup_env(tmp_path, log, bash_env, alias)
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 0, result.stderr


def _download_sandbox(tmp_path: Path, auth_exit: int = 0) -> tuple[Path, Path, Path]:
    root = tmp_path / "download repo with spaces"
    script = _copy_script(DOWNLOAD, root)
    log = tmp_path / "download.log"
    _executable(
        root / ".venv/bin/hf",
        "#!/usr/bin/env bash\n"
        "printf 'hf:%s\\n' \"$*\" >> \"$CALL_LOG\"\n"
        f"[[ \"$*\" == 'auth whoami' ]] && exit {auth_exit}\n"
        "exit 0\n",
    )
    _executable(
        root / "scripts/download_model.sh",
        "#!/usr/bin/env bash\n"
        "printf 'download:%s:model=%s:path=%s\\n' \"$1\" \"$H3_MODEL_DIR\" \"$PATH\" >> \"$CALL_LOG\"\n",
    )
    return root, script, log


@pytest.mark.parametrize("variant", ["fl2va", "ref2va", "both"])
def test_download_delegates_variant_and_default_model_directory(
    tmp_path: Path, variant: str
) -> None:
    root, script, log = _download_sandbox(tmp_path)
    env = os.environ.copy()
    env["CALL_LOG"] = str(log)
    result = subprocess.run(
        [str(script), variant], cwd=tmp_path, env=env, text=True, capture_output=True, check=False
    )
    assert result.returncode == 0, result.stderr
    assert f"download:{variant}:model={root / 'models/MiniMax-H3'}:" in log.read_text()
    assert str(root / ".venv/bin") in log.read_text()


def test_download_logs_in_only_when_needed_and_honors_custom_model_dir(tmp_path: Path) -> None:
    _, script, log = _download_sandbox(tmp_path, auth_exit=1)
    model_dir = tmp_path / "shared models/MiniMax-H3"
    env = os.environ.copy()
    env.update(CALL_LOG=str(log), H3_MODEL_DIR=str(model_dir))
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 0, result.stderr
    calls = log.read_text()
    assert "hf:auth whoami" in calls
    assert "hf:auth login" in calls
    assert f"download:fl2va:model={model_dir}:" in calls


def test_download_restores_modules_and_uses_project_hf_and_model(tmp_path: Path) -> None:
    root = tmp_path / "download-project-repo"
    script = _copy_script(DOWNLOAD, root)
    log = tmp_path / "download-project.log"
    project = tmp_path / "project"
    h3_env = project / "envs/h3"
    hf = _executable(
        h3_env / "bin/hf",
        "#!/usr/bin/env bash\nprintf 'project-hf:%s\\n' \"$*\" >> \"$CALL_LOG\"\n",
    )
    model = project / "models/MiniMax-H3"
    modules = project / "nibi-modules.sh"
    modules.parent.mkdir(parents=True, exist_ok=True)
    modules.write_text("printf 'modules-restored\\n' >> \"$CALL_LOG\"\n")
    _executable(
        root / "scripts/download_model.sh",
        "#!/usr/bin/env bash\nprintf 'download:%s:model=%s:path=%s\\n' \"$1\" \"$H3_MODEL_DIR\" \"$PATH\" >> \"$CALL_LOG\"\n",
    )
    (root / ".env").write_text(
        f"H3_PLATFORM=nibi\nH3_ENV_DIR={h3_env}\nH3_HF_BIN={hf}\n"
        f"H3_MODEL_DIR={model}\nH3_MODULES_FILE={modules}\n"
    )
    result = subprocess.run(
        [str(script)],
        env={**os.environ, "CALL_LOG": str(log), "VIRTUAL_ENV": str(h3_env)},
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    calls = log.read_text()
    assert "modules-restored" in calls
    assert "project-hf:auth whoami" in calls
    assert f"download:fl2va:model={model}:" in calls
    assert str(hf.parent) in calls


def test_download_rejects_bad_variant_and_missing_setup(tmp_path: Path) -> None:
    root = tmp_path / "repo"
    script = _copy_script(DOWNLOAD, root)
    bad = subprocess.run([str(script), "wrong"], text=True, capture_output=True, check=False)
    assert bad.returncode == 2
    assert "Usage:" in bad.stderr
    missing = subprocess.run([str(script)], text=True, capture_output=True, check=False)
    assert missing.returncode == 1
    assert "Run ./setup.sh first" in missing.stderr


@pytest.mark.parametrize("active_env", [None, "wrong"])
def test_nibi_download_requires_the_configured_environment(
    tmp_path: Path, active_env: str | None
) -> None:
    root, script, log = _download_sandbox(tmp_path)
    expected = tmp_path / "project/envs/h3"
    (root / ".env").write_text(f"H3_PLATFORM=nibi\nH3_ENV_DIR={expected}\n")
    env = {**os.environ, "CALL_LOG": str(log)}
    env.pop("VIRTUAL_ENV", None)
    if active_env:
        env["VIRTUAL_ENV"] = str(tmp_path / active_env)
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "source .venv/bin/activate" in result.stderr
    assert not log.exists() or "download:" not in log.read_text()


def _server_sandbox(
    tmp_path: Path, *, sglang_exits: bool = False, gateway_exits: bool = False
) -> tuple[Path, Path, Path]:
    root = tmp_path / "server repo with spaces"
    script = _copy_script(SERVER, root)
    state = tmp_path / "server-state"
    state.mkdir()
    model = root / "models/MiniMax-H3"
    (model / "FL2VA").mkdir(parents=True)
    (model / "model_index.json").write_text("{}")
    _executable(root / ".venv/bin/sglang", "#!/usr/bin/env bash\nexit 0\n")
    gateway_body = "#!/usr/bin/env bash\nexit 19\n" if gateway_exits else (
        "#!/usr/bin/env bash\n"
        "printf 'port=%s fl2va=%s\\n' \"${H3_GATEWAY_PORT:-}\" \"${H3_FL2VA_URL:-}\" > \"$SERVER_STATE/gateway-env\"\n"
        "while :; do sleep 1; done\n"
    )
    _executable(root / ".venv/bin/h3-gateway", gateway_body)
    if sglang_exits:
        launch = "#!/usr/bin/env bash\nexit 17\n"
    else:
        launch = (
            "#!/usr/bin/env bash\n"
            "printf 'model=%s profile=%s cuda=%s args=%s\\n' \"$H3_MODEL_PATH\" \"$H3_PROFILE\" "
            "\"$CUDA_VISIBLE_DEVICES\" \"$*\" > \"$SERVER_STATE/sglang-env\"\n"
            "while :; do sleep 1; done\n"
        )
    _executable(root / "deploy/start_sglang.sh", launch)
    fake_bin = tmp_path / "server-bin"
    fake_bin.mkdir()
    _executable(
        fake_bin / "nvidia-smi",
        "#!/usr/bin/env bash\n"
        "printf 'nvidia-smi:%s\\n' \"$*\" >> \"$SERVER_STATE/command-calls\"\n"
        "printf '%s\\n' \"${FAKE_GPU_NAME:-NVIDIA H100 80GB HBM3}\"\n",
    )
    for forbidden in ("salloc", "sbatch", "scancel"):
        _executable(
            fake_bin / forbidden,
            "#!/usr/bin/env bash\n"
            f"printf '{forbidden}:%s\\n' \"$*\" >> \"$SERVER_STATE/command-calls\"\n"
            "exit 97\n",
        )
    _executable(
        fake_bin / "curl",
        "#!/usr/bin/env bash\n"
        "printf '%s\\n' \"$*\" >> \"$SERVER_STATE/curl-calls\"\n"
        "[[ \"${FAKE_CURL_EXIT:-0}\" != 0 ]] && exit \"$FAKE_CURL_EXIT\"\n"
        "if [[ \"$*\" == */healthz* ]]; then [[ -f \"$SERVER_STATE/gateway-env\" ]]; exit; fi\n"
        "if [[ \"$*\" == */health* ]]; then [[ -f \"$SERVER_STATE/sglang-env\" ]]; exit; fi\n"
        "exit 22\n",
    )
    return root, script, state


def _server_env(tmp_path: Path, state: Path, **overrides: str) -> dict[str, str]:
    env = os.environ.copy()
    env.update(
        PATH=f"{tmp_path / 'server-bin'}{os.pathsep}{env['PATH']}",
        SERVER_STATE=str(state),
        H3_STARTUP_TIMEOUT_SECONDS="10",
    )
    env.update(overrides)
    return env


def test_server_start_status_stop_and_restart_with_defaults(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path)
    env = _server_env(tmp_path, state)
    try:
        started = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
        assert started.returncode == 0, started.stderr
        assert "Server is ready. Run: ./generate.sh" in started.stdout
        assert (root / "logs/sglang.log").is_file()
        assert (root / "logs/gateway.log").is_file()
        for _ in range(100):
            if (state / "sglang-env").exists():
                break
            time.sleep(0.01)
        assert "profile=auto cuda=0 args=fl2va" in (state / "sglang-env").read_text()
        calls = (state / "command-calls").read_text()
        assert "nvidia-smi:--query-gpu=name --format=csv,noheader" in calls
        assert not any(name in calls for name in ("salloc:", "sbatch:", "scancel:"))
        status = subprocess.run(
            [str(script), "status"], env=env, text=True, capture_output=True, check=False
        )
        assert status.returncode == 0
        assert "SGLang: running" in status.stdout
        assert "Gateway: running" in status.stdout

        duplicate = subprocess.run(
            [str(script), "start"], env=env, text=True, capture_output=True, check=False
        )
        assert duplicate.returncode == 1
        assert "Server is already running" in duplicate.stderr

        restarted = subprocess.run(
            [str(script), "restart"], env=env, text=True, capture_output=True, check=False
        )
        assert restarted.returncode == 0, restarted.stderr
        assert "Server is ready" in restarted.stdout
    finally:
        subprocess.run([str(script), "stop"], env=env, capture_output=True, check=False)

    stopped = subprocess.run(
        [str(script), "status"], env=env, text=True, capture_output=True, check=False
    )
    assert stopped.stdout == "SGLang: stopped\nGateway: stopped\n"
    assert not list((root / ".run").glob("*.pid"))


def test_server_honors_model_gpu_and_profile_environment(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path)
    custom = tmp_path / "custom model path"
    (custom / "FL2VA").mkdir(parents=True)
    (custom / "model_index.json").write_text("{}")
    env = _server_env(
        tmp_path,
        state,
        H3_MODEL_PATH=str(custom),
        H3_PROFILE="h100x1",
        CUDA_VISIBLE_DEVICES="GPU-one,GPU-two,GPU-three,GPU-four",
    )
    try:
        result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
        assert result.returncode == 0, result.stderr
        for _ in range(100):
            if (state / "sglang-env").exists():
                break
            time.sleep(0.01)
        launched = (state / "sglang-env").read_text()
        assert f"model={custom}" in launched
        assert "profile=h100x1" in launched
        assert "cuda=GPU-one,GPU-two,GPU-three,GPU-four" in launched
    finally:
        subprocess.run([str(script), "stop"], env=env, capture_output=True, check=False)


def test_server_propagates_custom_inference_and_gateway_ports(tmp_path: Path) -> None:
    _, script, state = _server_sandbox(tmp_path)
    env = _server_env(tmp_path, state, H3_INFERENCE_PORT="39101", H3_GATEWAY_PORT="39102")
    try:
        result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
        assert result.returncode == 0, result.stderr
        assert "39101/health" in (state / "curl-calls").read_text()
        assert "39102/healthz" in (state / "curl-calls").read_text()
        gateway_env = (state / "gateway-env").read_text()
        assert "port=39102" in gateway_env
        assert "fl2va=http://127.0.0.1:39101" in gateway_env
    finally:
        subprocess.run([str(script), "stop"], env=env, capture_output=True, check=False)


def test_server_rejects_missing_environment_and_model(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path)
    env = _server_env(tmp_path, state)
    (root / ".venv/bin/h3-gateway").unlink()
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "Run ./setup.sh first" in result.stderr

    _executable(root / ".venv/bin/h3-gateway", "#!/usr/bin/env bash\nexit 0\n")
    shutil.rmtree(root / "models/MiniMax-H3/FL2VA")
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "Run ./download_models.sh first" in result.stderr


def test_server_refuses_non_h100_gpu(tmp_path: Path) -> None:
    _, script, state = _server_sandbox(tmp_path)
    env = _server_env(tmp_path, state, FAKE_GPU_NAME="NVIDIA A100-SXM4-80GB")
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "No full H100 is visible" in result.stderr
    assert not (state / "sglang-env").exists()


def test_server_refuses_when_nvidia_smi_is_unavailable(tmp_path: Path) -> None:
    _, script, state = _server_sandbox(tmp_path)
    (tmp_path / "server-bin/nvidia-smi").unlink()
    isolated = tmp_path / "no-gpu-bin"
    isolated.mkdir()
    for command in ("bash", "awk", "dirname", "mkdir", "python3", "rm"):
        target = shutil.which(command)
        assert target
        (isolated / command).symlink_to(target)
    env = _server_env(tmp_path, state)
    env["PATH"] = str(isolated)
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "No NVIDIA GPU is visible" in result.stderr


@pytest.mark.parametrize("action", ["status", "stop"])
def test_nibi_server_status_and_stop_do_not_require_activation(tmp_path: Path, action: str) -> None:
    root, script, state = _server_sandbox(tmp_path)
    expected = tmp_path / "project/envs/h3"
    (root / ".env").write_text(f"H3_PLATFORM=nibi\nH3_ENV_DIR={expected}\n")
    env = _server_env(tmp_path, state)
    env.pop("VIRTUAL_ENV", None)
    result = subprocess.run([str(script), action], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 0, result.stderr
    assert "Activate" not in result.stderr


@pytest.mark.parametrize("active_env", [None, "wrong-env"])
def test_nibi_server_start_requires_the_configured_environment(
    tmp_path: Path, active_env: str | None
) -> None:
    root, script, state = _server_sandbox(tmp_path)
    expected = tmp_path / "project/envs/h3"
    (root / ".env").write_text(f"H3_PLATFORM=nibi\nH3_ENV_DIR={expected}\n")
    env = _server_env(tmp_path, state)
    env.pop("VIRTUAL_ENV", None)
    if active_env:
        env["VIRTUAL_ENV"] = str(tmp_path / active_env)
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "source .venv/bin/activate" in result.stderr
    assert not (state / "sglang-env").exists()


def test_nibi_restart_without_activation_does_not_stop_running_server(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path)
    env = _server_env(tmp_path, state)
    try:
        started = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
        assert started.returncode == 0, started.stderr
        expected = tmp_path / "project/envs/h3"
        (root / ".env").write_text(f"H3_PLATFORM=nibi\nH3_ENV_DIR={expected}\n")
        env.pop("VIRTUAL_ENV", None)
        restarted = subprocess.run(
            [str(script), "restart"], env=env, text=True, capture_output=True, check=False
        )
        assert restarted.returncode == 1
        assert "source .venv/bin/activate" in restarted.stderr
        status = subprocess.run(
            [str(script), "status"], env=env, text=True, capture_output=True, check=False
        )
        assert "SGLang: running" in status.stdout
        assert "Gateway: running" in status.stdout
    finally:
        subprocess.run([str(script), "stop"], env=env, capture_output=True, check=False)


def test_server_restores_modules_and_uses_project_binaries_and_model(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path)
    project = tmp_path / "project"
    h3_env = project / "envs/h3"
    sglang = _executable(h3_env / "bin/sglang", "#!/usr/bin/env bash\nexit 0\n")
    gateway = _executable(
        h3_env / "bin/h3-gateway",
        "#!/usr/bin/env bash\nprintf 'project-gateway\\n' >> \"$SERVER_STATE/command-calls\"\n"
        "printf 'ready\\n' > \"$SERVER_STATE/gateway-env\"\nwhile :; do sleep 1; done\n",
    )
    model = project / "models/MiniMax-H3"
    (model / "FL2VA").mkdir(parents=True)
    (model / "model_index.json").write_text("{}")
    modules = project / "nibi-modules.sh"
    modules.write_text("printf 'modules-restored\\n' >> \"$SERVER_STATE/command-calls\"\n")
    (root / ".env").write_text(
        f"H3_PLATFORM=nibi\nH3_ENV_DIR={h3_env}\nH3_SGLANG_BIN={sglang}\n"
        f"H3_GATEWAY_BIN={gateway}\nH3_MODEL_PATH={model}\nH3_MODULES_FILE={modules}\n"
    )
    env = _server_env(
        tmp_path,
        state,
        H3_STARTUP_TIMEOUT_SECONDS="10",
        VIRTUAL_ENV=str(h3_env),
    )
    try:
        result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
        assert result.returncode == 0, result.stderr
        calls = (state / "command-calls").read_text()
        assert "modules-restored" in calls
        assert "project-gateway" in calls
        assert f"model={model}" in (state / "sglang-env").read_text()
    finally:
        subprocess.run([str(script), "stop"], env=env, capture_output=True, check=False)


def test_server_cleans_pid_files_when_sglang_dies_at_startup(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path, sglang_exits=True)
    env = _server_env(tmp_path, state, FAKE_CURL_EXIT="22")
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "SGLang stopped during startup" in result.stderr
    assert not list((root / ".run").glob("*.pid"))


def test_server_cleans_both_processes_when_gateway_dies_at_startup(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path, gateway_exits=True)
    env = _server_env(tmp_path, state)
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "Gateway" in result.stderr
    assert not list((root / ".run").glob("*.pid"))


def test_server_timeout_stops_spawned_process_and_cleans_pid_files(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path)
    env = _server_env(tmp_path, state, FAKE_CURL_EXIT="22", H3_STARTUP_TIMEOUT_SECONDS="0")
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "SGLang startup timed out" in result.stderr
    assert not list((root / ".run").glob("*.pid"))


def test_server_removes_nonnumeric_and_dead_stale_pid_files(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path)
    env = _server_env(tmp_path, state)
    (root / ".run").mkdir()
    (root / ".run/sglang.pid").write_text("not-a-pid\n")
    (root / ".run/gateway.pid").write_text("99999999\n")
    try:
        result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
        assert result.returncode == 0, result.stderr
    finally:
        subprocess.run([str(script), "stop"], env=env, capture_output=True, check=False)


@pytest.mark.parametrize("port_variable", ["H3_INFERENCE_PORT", "H3_GATEWAY_PORT"])
def test_server_rejects_an_existing_service_without_owned_pid(
    tmp_path: Path, port_variable: str
) -> None:
    root, script, state = _server_sandbox(tmp_path)
    listener = socket.socket()
    listener.bind(("127.0.0.1", 0))
    listener.listen()
    port = listener.getsockname()[1]
    env = _server_env(tmp_path, state, **{port_variable: str(port)})
    try:
        result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
        assert result.returncode == 1
        assert "already" in result.stderr.lower() or "in use" in result.stderr.lower()
        assert not (state / "sglang-env").exists(), "launcher ran despite an existing service"
        assert not list((root / ".run").glob("*.pid"))
    finally:
        listener.close()


def test_server_does_not_kill_unrelated_process_from_stale_pid_file(tmp_path: Path) -> None:
    root, script, state = _server_sandbox(tmp_path)
    env = _server_env(tmp_path, state)
    (root / ".run").mkdir()
    unrelated = subprocess.Popen([sys.executable, "-c", "import time; time.sleep(60)"])
    try:
        (root / ".run/sglang.pid").write_text(f"{unrelated.pid}\n")
        result = subprocess.run(
            [str(script), "stop"], env=env, text=True, capture_output=True, check=False
        )
        assert result.returncode == 0, result.stderr
        assert unrelated.poll() is None, "stale PID file caused an unrelated live process to be killed"
    finally:
        if unrelated.poll() is None:
            unrelated.terminate()
        unrelated.wait(timeout=5)


def test_root_generate_preserves_all_arguments_and_exit_status(tmp_path: Path) -> None:
    root = tmp_path / "generate repo with spaces"
    script = _copy_script(GENERATE, root)
    output = tmp_path / "delegated args"
    _executable(
        root / "scripts/generate.sh",
        "#!/usr/bin/env bash\nprintf '<%s>\\n' \"$@\"\nexit \"${DELEGATE_EXIT:-0}\"\n",
    )
    result = subprocess.run(
        [str(script), "prompt with spaces", str(output)],
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0
    assert result.stdout.splitlines() == ["<prompt with spaces>", f"<{output}>"]
    failed = subprocess.run(
        [str(script)],
        env={**os.environ, "DELEGATE_EXIT": "23"},
        text=True,
        capture_output=True,
        check=False,
    )
    assert failed.returncode == 23


@pytest.mark.parametrize("active_env", [None, "wrong-env"])
def test_nibi_generate_requires_the_configured_environment(
    tmp_path: Path, active_env: str | None
) -> None:
    root = tmp_path / "generate-nibi-repo"
    script = _copy_script(GENERATE, root)
    expected = tmp_path / "project/envs/h3"
    (root / ".env").write_text(f"H3_PLATFORM=nibi\nH3_ENV_DIR={expected}\n")
    marker = tmp_path / "delegated"
    _executable(
        root / "scripts/generate.sh",
        f"#!/usr/bin/env bash\nprintf called > {shlex.quote(str(marker))}\n",
    )
    env = os.environ.copy()
    env.pop("VIRTUAL_ENV", None)
    if active_env:
        env["VIRTUAL_ENV"] = str(tmp_path / active_env)
    result = subprocess.run([str(script)], env=env, text=True, capture_output=True, check=False)
    assert result.returncode == 1
    assert "source .venv/bin/activate" in result.stderr
    assert not marker.exists()


def test_nibi_generate_accepts_the_configured_environment_via_symlink(tmp_path: Path) -> None:
    root = tmp_path / "generate-nibi-active-repo"
    script = _copy_script(GENERATE, root)
    expected = tmp_path / "project/envs/h3"
    expected.mkdir(parents=True)
    alias = tmp_path / "active-env-link"
    alias.symlink_to(expected, target_is_directory=True)
    (root / ".env").write_text(f"H3_PLATFORM=nibi\nH3_ENV_DIR={expected}\n")
    _executable(root / "scripts/generate.sh", "#!/usr/bin/env bash\nprintf '<%s>\\n' \"$@\"\n")
    result = subprocess.run(
        [str(script), "prompt", "output.mp4"],
        env={**os.environ, "VIRTUAL_ENV": str(alias)},
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert result.stdout.splitlines() == ["<prompt>", "<output.mp4>"]


@pytest.mark.parametrize("script", [SETUP, DOWNLOAD, SERVER, GENERATE])
def test_easy_scripts_are_executable_and_valid_bash(script: Path) -> None:
    assert script.stat().st_mode & stat.S_IXUSR
    result = subprocess.run(["bash", "-n", str(script)], text=True, capture_output=True)
    assert result.returncode == 0, result.stderr


@pytest.mark.parametrize(
    "script",
    [
        REPO / "scripts/require_active_env.sh",
        REPO / "scripts/bootstrap_gateway.sh",
        REPO / "scripts/bootstrap_sglang.sh",
        REPO / "deploy/start_sglang.sh",
    ],
)
def test_unified_environment_helpers_are_valid_bash(script: Path) -> None:
    result = subprocess.run(["bash", "-n", str(script)], text=True, capture_output=True)
    assert result.returncode == 0, result.stderr


def test_easy_workflow_never_manages_slurm_allocations() -> None:
    forbidden = ("salloc", "sbatch", "scancel")
    for script in (SETUP, DOWNLOAD, SERVER, GENERATE):
        content = script.read_text()
        assert not any(command in content for command in forbidden), script


def test_cuda_tile_is_locked_to_nvidia_cp311_x86_64_wheel() -> None:
    project = tomllib.loads((REPO / "pyproject.toml").read_text())
    inference = project["project"]["optional-dependencies"]["inference"]
    assert "cuda-tile; sys_platform == 'linux'" in inference
    assert project["tool"]["uv"]["sources"]["cuda-tile"] == {"index": "nvidia"}
    assert project["tool"]["uv"]["index"] == [
        {"name": "nvidia", "url": "https://pypi.nvidia.com", "explicit": True}
    ]

    lock = tomllib.loads((REPO / "uv.lock").read_text())
    cuda_tile = next(package for package in lock["package"] if package["name"] == "cuda-tile")
    assert cuda_tile["source"] == {"registry": "https://pypi.nvidia.com/"}
    assert "sdist" not in cuda_tile
    wheel_urls = [wheel["url"] for wheel in cuda_tile["wheels"]]
    assert any(
        url.startswith("https://pypi.nvidia.com/cuda-tile/")
        and "-cp311-cp311-manylinux2014_x86_64.whl" in url
        for url in wheel_urls
    )
    assert not any("files.pythonhosted.org" in url for url in wheel_urls)


def test_sglang_lock_supports_the_minimax_h3_cli() -> None:
    project = tomllib.loads((REPO / "pyproject.toml").read_text())
    inference = project["project"]["optional-dependencies"]["inference"]
    assert "sglang[diffusion]>=0.5.17; sys_platform == 'linux'" in inference

    lock = tomllib.loads((REPO / "uv.lock").read_text())
    sglang = next(package for package in lock["package"] if package["name"] == "sglang")
    assert sglang["version"] == "0.5.20"
